create table BookDetailsOne(BookAuthor char(45),BookName char(50),BookType char(20),BookPages int(4),BookPrice double(6,2),BookID int(4));
desc BookDetailsOne;
insert into BookDetailsOne values("Rbond","The blue umbrella","Story",56,23.50,1234);
insert into BookDetailsOne values("Abcd","Core Java Fundamental","Technical",56,145.90,1878);
insert into BookDetailsOne values("Rbond","Time stops at shamli","Story",56,18.90,1786);
insert into BookDetailsOne values("ypk","C Fundamental","Technical",56,555.55,1216);
insert into BookDetailsOne values("Rbond","Java Fundamental","Technical",56,35.90,2700);
insert into BookDetailsOne values("Pallhavi Joshi","No time","Fiction",56,109.90,4321);
insert into BookDetailsOne values("ypk","C++ Fundamental","Technical",56,276.00,1111);
insert into BookDetailsOne values("Pallhavi Joshi","Out of box","Fiction",56,78.21,3434);
insert into BookDetailsOne values("ypk","C Fundamental","Non Fiction",56,55.89,1412);
commit;
select * from BookDetailsOne;
select BookAuthor,BookName from bookdetailsone where BookType="Story";
select * from BookDetailsOne where BookPrice<109;
select count(*) from BookDetailsOne where BookAuthor="ypk";
select * from BookDetailsOne where BookID!=1111;
select * from BookDetailsOne where BookID NOT IN (1111);
select * from BookDetailsOne where  BookPrice BETWEEN 35 AND 100;
select * from BookDetailsOne where BookID NOT IN (1234,2700,4321);
select * from BookDetailsOne where BookAuthor LIKE '%i';
select BookName,BookPrice || BookID from BookDetailsOne;
select BookName,concat(BookPrice,BookID) from BookDetailsOne;
select concat(BookPrice,' **** ',BookID,' **** ',BookAuthor) from BookDetailsOne;
select * from BookDetailsOne limit 6;
select count(*) from BookDetailsOne where BookAuthor IN ('ypk','Rbond');
select BookDetailsOne.*,BookPrice+BookPrice*5/100 from BookDetailsOne where BookAuthor = 'ypk';
select BookPrice+BookPrice*10/100 from BookDetailsOne where BookAuthor = 'ypk';
select avg(BookPrice) from BookDetailsOne where BookType='story';
select sum(BookPrice) from BookDetailsOne;
select avg(BookPrice) from BookDetailsOne;
select max(BookPrice) from BookDetailsOne;
select min(BookPrice) from BookDetailsOne;
select avg(BookPrice) AS BP from BookDetailsOne;
select sum(BookPrice) from BookDetailsOne where BookPrice NOT IN(23.50,18.90);
select * from BookDetailsOne;
select * from BookDetailsOne Order By BookPrice;
select * from BookDetailsOne Order By BookPrice desc;
select BookName,BookAuthor,BookPrice from BookDetailsOne
where BookAuthor='ypk'Order BY BookPrice;
select count(*) from BookDetailsOne where BookName NOT IN('No time','C fundamental');
select * from BookDetailsOne Order By  BookPrice desc limit 3;